/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.foodcitysystem.view;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Lenovo™
 */
public class BackOffice extends javax.swing.JFrame {

    /**
     * Creates new form BackOffice
     */
    public BackOffice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnlDashBoard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlSupplier = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pnlGRN = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pnlStock = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        pnlPurchases = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        pnlSales = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlItem = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        pnlGrossProfit = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pnlPurchaseOrder = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        pnlCustomer = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        pnlMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1150, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(36, 113, 163));
        jPanel2.setForeground(new java.awt.Color(36, 113, 163));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("WARNASIRI FOOD CITY-BACK OFFICE");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 470, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 900, 80));

        pnlDashBoard.setBackground(new java.awt.Color(36, 113, 163));
        pnlDashBoard.setPreferredSize(new java.awt.Dimension(300, 700));
        pnlDashBoard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/foodcitysystem/icon/food-city-tharuka-120.png-white.png"))); // NOI18N
        pnlDashBoard.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 220, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" WARNASIRI");
        pnlDashBoard.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 170, 30));

        pnlSupplier.setBackground(new java.awt.Color(36, 113, 163));
        pnlSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlSupplierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSupplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSupplierMouseExited(evt);
            }
        });
        pnlSupplier.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/foodcitysystem/icon/hotel-supplier (1).png"))); // NOI18N
        jLabel5.setText("  supplier");
        pnlSupplier.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, 200, 50));

        pnlDashBoard.add(pnlSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 250, 40));

        pnlGRN.setBackground(new java.awt.Color(36, 113, 163));
        pnlGRN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlGRNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlGRNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlGRNMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/foodcitysystem/icon/invoice.png"))); // NOI18N
        jLabel7.setText(" GRN");

        javax.swing.GroupLayout pnlGRNLayout = new javax.swing.GroupLayout(pnlGRN);
        pnlGRN.setLayout(pnlGRNLayout);
        pnlGRNLayout.setHorizontalGroup(
            pnlGRNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGRNLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlGRNLayout.setVerticalGroup(
            pnlGRNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGRNLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(49, 49, 49))
        );

        pnlDashBoard.add(pnlGRN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 250, 40));

        pnlStock.setBackground(new java.awt.Color(36, 113, 163));
        pnlStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlStockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlStockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlStockMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/foodcitysystem/icon/bar-graph-with-dollar-sign.png"))); // NOI18N
        jLabel10.setText(" Stock");

        javax.swing.GroupLayout pnlStockLayout = new javax.swing.GroupLayout(pnlStock);
        pnlStock.setLayout(pnlStockLayout);
        pnlStockLayout.setHorizontalGroup(
            pnlStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStockLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlStockLayout.setVerticalGroup(
            pnlStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStockLayout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlDashBoard.add(pnlStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 250, 40));

        pnlPurchases.setBackground(new java.awt.Color(36, 113, 163));
        pnlPurchases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPurchasesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlPurchasesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlPurchasesMouseExited(evt);
            }
        });
        pnlPurchases.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/foodcitysystem/icon/purchase-order.png"))); // NOI18N
        jLabel12.setText(" Purchases");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        pnlPurchases.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 190, 30));

        pnlDashBoard.add(pnlPurchases, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 250, 40));

        pnlSales.setBackground(new java.awt.Color(36, 113, 163));
        pnlSales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlSalesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSalesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSalesMouseExited(evt);
            }
        });
        pnlSales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/foodcitysystem/icon/badge.png"))); // NOI18N
        jLabel11.setText(" Sales");
        pnlSales.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 180, -1));

        pnlDashBoard.add(pnlSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 250, 40));
        pnlDashBoard.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 250, 10));

        pnlItem.setBackground(new java.awt.Color(36, 113, 163));
        pnlItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlItemMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/foodcitysystem/icon/shopping-cart.png"))); // NOI18N
        jLabel8.setText("   Item");

        javax.swing.GroupLayout pnlItemLayout = new javax.swing.GroupLayout(pnlItem);
        pnlItem.setLayout(pnlItemLayout);
        pnlItemLayout.setHorizontalGroup(
            pnlItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlItemLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlItemLayout.setVerticalGroup(
            pnlItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlItemLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlDashBoard.add(pnlItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 250, 40));
        pnlDashBoard.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 250, 0));
        pnlDashBoard.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 250, 10));
        pnlDashBoard.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 250, 10));
        pnlDashBoard.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 568, 250, -1));
        pnlDashBoard.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 250, 10));
        pnlDashBoard.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 250, 10));

        pnlGrossProfit.setBackground(new java.awt.Color(36, 113, 163));
        pnlGrossProfit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlGrossProfitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlGrossProfitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlGrossProfitMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/foodcitysystem/icon/coins.png"))); // NOI18N
        jLabel9.setText("  Gross Profit");

        javax.swing.GroupLayout pnlGrossProfitLayout = new javax.swing.GroupLayout(pnlGrossProfit);
        pnlGrossProfit.setLayout(pnlGrossProfitLayout);
        pnlGrossProfitLayout.setHorizontalGroup(
            pnlGrossProfitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGrossProfitLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        pnlGrossProfitLayout.setVerticalGroup(
            pnlGrossProfitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGrossProfitLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlDashBoard.add(pnlGrossProfit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 250, 40));

        pnlPurchaseOrder.setBackground(new java.awt.Color(36, 113, 163));
        pnlPurchaseOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPurchaseOrderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlPurchaseOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlPurchaseOrderMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/foodcitysystem/icon/purchase-order.png"))); // NOI18N
        jLabel6.setText(" Purchase Order");

        javax.swing.GroupLayout pnlPurchaseOrderLayout = new javax.swing.GroupLayout(pnlPurchaseOrder);
        pnlPurchaseOrder.setLayout(pnlPurchaseOrderLayout);
        pnlPurchaseOrderLayout.setHorizontalGroup(
            pnlPurchaseOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPurchaseOrderLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        pnlPurchaseOrderLayout.setVerticalGroup(
            pnlPurchaseOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPurchaseOrderLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pnlDashBoard.add(pnlPurchaseOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 250, 50));
        pnlDashBoard.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 250, 10));

        pnlCustomer.setBackground(new java.awt.Color(36, 113, 163));
        pnlCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCustomerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlCustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlCustomerMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/foodcitysystem/icon/call-service.png"))); // NOI18N
        jLabel4.setText("  Customer");

        javax.swing.GroupLayout pnlCustomerLayout = new javax.swing.GroupLayout(pnlCustomer);
        pnlCustomer.setLayout(pnlCustomerLayout);
        pnlCustomerLayout.setHorizontalGroup(
            pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCustomerLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        pnlCustomerLayout.setVerticalGroup(
            pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDashBoard.add(pnlCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, 40));
        pnlDashBoard.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 250, 10));
        pnlDashBoard.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 250, 10));

        jPanel1.add(pnlDashBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 660));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 1150, 40));

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );

        jPanel1.add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 800, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnlSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSupplierMouseClicked

        Supplier supplier = new Supplier();
        pnlMain.removeAll();
        supplier.setSize(pnlMain.getSize());
        supplier.setVisible(true);
        pnlMain.add(supplier);
        pnlMain.revalidate();
        pnlMain.repaint();

    }//GEN-LAST:event_pnlSupplierMouseClicked

    private void pnlSupplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSupplierMouseEntered
        pnlSupplier.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_pnlSupplierMouseEntered

    private void pnlItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlItemMouseClicked
        Item item = new Item();
        pnlMain.removeAll();
        item.setSize(pnlMain.getSize());
        item.setVisible(true);
        pnlMain.add(item);
        pnlMain.revalidate();
        pnlMain.repaint();
    }//GEN-LAST:event_pnlItemMouseClicked

    private void pnlCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCustomerMouseClicked

        Customer customer = new Customer();
        pnlMain.removeAll();
        customer.setSize(pnlMain.getSize());
        customer.setVisible(true);
        pnlMain.add(customer);
        pnlMain.revalidate();
        pnlMain.repaint();

    }//GEN-LAST:event_pnlCustomerMouseClicked

    private void pnlPurchaseOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPurchaseOrderMouseClicked
        PurchaseOrder purchaseOrder = new PurchaseOrder();
        pnlMain.removeAll();
        purchaseOrder.setSize(pnlMain.getSize());
        purchaseOrder.setVisible(true);
        pnlMain.add(purchaseOrder);
        pnlMain.revalidate();
        pnlMain.repaint();

    }//GEN-LAST:event_pnlPurchaseOrderMouseClicked

    private void pnlGRNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGRNMouseClicked
        GRN grn = new GRN();
        pnlMain.removeAll();
        grn.setSize(pnlMain.getSize());
        grn.setVisible(true);
        pnlMain.add(grn);
        pnlMain.revalidate();
        pnlMain.repaint();


    }//GEN-LAST:event_pnlGRNMouseClicked

    private void pnlStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlStockMouseClicked
        Stock stock = new Stock();
        pnlMain.removeAll();
        stock.setSize(pnlMain.getSize());
        stock.setVisible(true);
        pnlMain.add(stock);
        pnlMain.revalidate();
        pnlMain.repaint();
    }//GEN-LAST:event_pnlStockMouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked

    }//GEN-LAST:event_jLabel12MouseClicked

    private void pnlPurchasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPurchasesMouseClicked

    }//GEN-LAST:event_pnlPurchasesMouseClicked

    private void pnlSalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSalesMouseClicked

    }//GEN-LAST:event_pnlSalesMouseClicked

    private void pnlGrossProfitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGrossProfitMouseClicked

    }//GEN-LAST:event_pnlGrossProfitMouseClicked

    private void pnlItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlItemMouseEntered
        pnlItem.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_pnlItemMouseEntered

    private void pnlCustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCustomerMouseEntered
        pnlCustomer.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_pnlCustomerMouseEntered

    private void pnlPurchaseOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPurchaseOrderMouseEntered
        pnlPurchaseOrder.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_pnlPurchaseOrderMouseEntered

    private void pnlGRNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGRNMouseEntered
        pnlGRN.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_pnlGRNMouseEntered

    private void pnlStockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlStockMouseEntered
        pnlStock.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_pnlStockMouseEntered

    private void pnlPurchasesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPurchasesMouseEntered
        pnlPurchases.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_pnlPurchasesMouseEntered

    private void pnlSalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSalesMouseEntered
        pnlSales.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_pnlSalesMouseEntered

    private void pnlGrossProfitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGrossProfitMouseEntered
        pnlGrossProfit.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_pnlGrossProfitMouseEntered

    private void pnlSupplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSupplierMouseExited
        pnlSupplier.setBackground(new Color(36, 113, 163));
    }//GEN-LAST:event_pnlSupplierMouseExited

    private void pnlItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlItemMouseExited
        pnlItem.setBackground(new Color(36, 113, 163));
    }//GEN-LAST:event_pnlItemMouseExited

    private void pnlCustomerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCustomerMouseExited
        pnlCustomer.setBackground(new Color(36, 113, 163));
    }//GEN-LAST:event_pnlCustomerMouseExited

    private void pnlPurchaseOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPurchaseOrderMouseExited
        pnlPurchaseOrder.setBackground(new Color(36, 113, 163));
    }//GEN-LAST:event_pnlPurchaseOrderMouseExited

    private void pnlGRNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGRNMouseExited
        pnlGRN.setBackground(new Color(36, 113, 163));
    }//GEN-LAST:event_pnlGRNMouseExited

    private void pnlStockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlStockMouseExited
        pnlStock.setBackground(new Color(36, 113, 163));
    }//GEN-LAST:event_pnlStockMouseExited

    private void pnlPurchasesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPurchasesMouseExited
        pnlPurchases.setBackground(new Color(36, 113, 163));
    }//GEN-LAST:event_pnlPurchasesMouseExited

    private void pnlSalesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSalesMouseExited
        pnlSales.setBackground(new Color(36, 113, 163));
    }//GEN-LAST:event_pnlSalesMouseExited

    private void pnlGrossProfitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGrossProfitMouseExited
        pnlGrossProfit.setBackground(new Color(36, 113, 163));
    }//GEN-LAST:event_pnlGrossProfitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BackOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BackOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BackOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BackOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BackOffice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel pnlCustomer;
    private javax.swing.JPanel pnlDashBoard;
    private javax.swing.JPanel pnlGRN;
    private javax.swing.JPanel pnlGrossProfit;
    private javax.swing.JPanel pnlItem;
    private static javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlPurchaseOrder;
    private javax.swing.JPanel pnlPurchases;
    private javax.swing.JPanel pnlSales;
    private javax.swing.JPanel pnlStock;
    private javax.swing.JPanel pnlSupplier;
    // End of variables declaration//GEN-END:variables
    public static JPanel getPanelMain() {
        return pnlMain;
    }
}
