/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.foodcitysystem.view;

import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import lk.ijse.foodcitysystem.controller.ItemCategoryController;
import lk.ijse.foodcitysystem.controller.ItemController;
import lk.ijse.foodcitysystem.core.dto.ItemCategoryDTO;
import lk.ijse.foodcitysystem.core.dto.ItemDTO;

/**
 *
 * @author Lenovo™
 */
public class Item extends javax.swing.JPanel {

    /**
     * Creates new form Item
     */
    public Item() {
        initComponents();
        loadAllCategoryNames();
        loadAllItems();
        
        tblItems.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        @Override
            public void valueChanged(ListSelectionEvent e) {
                
                if (tblItems.getSelectedRow() == -1) return;
                
                String itemCode= tblItems.getValueAt(tblItems.getSelectedRow(), 0).toString();
                String description= tblItems.getValueAt(tblItems.getSelectedRow(), 1).toString();
                String categoryName= tblItems.getValueAt(tblItems.getSelectedRow(), 2).toString();
                String categoryCode= tblItems.getValueAt(tblItems.getSelectedRow(), 3).toString();
                
                
                txtItemCode.setText(itemCode);
                txtDescription.setText(description);
                cmbCategoryName.setSelectedItem(categoryName);
                txtCategoryCode2.setText(categoryCode);
            }
        });        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItems = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        txtCategoryCode2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCategoryCode = new javax.swing.JTextField();
        txtCategoryName1 = new javax.swing.JTextField();
        txtItemCode = new javax.swing.JTextField();
        cmbCategoryName = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        pnlSave1 = new javax.swing.JPanel();
        lblSave1 = new javax.swing.JLabel();
        pnlEdit1 = new javax.swing.JPanel();
        lblUpdate1 = new javax.swing.JLabel();
        pnlRemove1 = new javax.swing.JPanel();
        lblRemove1 = new javax.swing.JLabel();
        pnlClear1 = new javax.swing.JPanel();
        lblClear1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        pnlSave2 = new javax.swing.JPanel();
        lblSave2 = new javax.swing.JLabel();
        pnlEdit2 = new javax.swing.JPanel();
        lblUpdate2 = new javax.swing.JLabel();
        pnlRemove2 = new javax.swing.JPanel();
        lblRemove2 = new javax.swing.JLabel();
        pnlClear2 = new javax.swing.JPanel();
        lblClear2 = new javax.swing.JLabel();
        pnlNewCategory = new javax.swing.JPanel();
        lblNewCategory = new javax.swing.JLabel();
        pnlNewCategory2 = new javax.swing.JPanel();
        lblNewItem = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 580));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(36, 113, 163));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/foodcitysystem/icon/list.png"))); // NOI18N
        jLabel1.setText("Item");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(323, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(247, 247, 247))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setFocusCycleRoot(true);
        jPanel4.setPreferredSize(new java.awt.Dimension(800, 0));

        tblItems.setBackground(new java.awt.Color(249, 249, 249));
        tblItems.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Description", "CategotyCode", "CategoryName"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblItems);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Category Code");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Item Code");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Description");

        txtDescription.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDescription.setBorder(null);
        txtDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescriptionActionPerformed(evt);
            }
        });

        txtCategoryCode2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCategoryCode2.setBorder(null);
        txtCategoryCode2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoryCode2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Category Name");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Item Category");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Category Name");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Category Code");

        txtCategoryCode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCategoryCode.setBorder(null);
        txtCategoryCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoryCodeActionPerformed(evt);
            }
        });

        txtCategoryName1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCategoryName1.setBorder(null);
        txtCategoryName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoryName1ActionPerformed(evt);
            }
        });

        txtItemCode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtItemCode.setBorder(null);
        txtItemCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemCodeActionPerformed(evt);
            }
        });

        cmbCategoryName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCategoryNameItemStateChanged(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("Item ");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        pnlSave1.setBackground(new java.awt.Color(204, 204, 204));
        pnlSave1.setPreferredSize(new java.awt.Dimension(90, 40));

        lblSave1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSave1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/foodcitysystem/icon/save-icon-silhouette.png"))); // NOI18N
        lblSave1.setText(" ");
        lblSave1.setPreferredSize(new java.awt.Dimension(90, 40));
        lblSave1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSave1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSave1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSave1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlSave1Layout = new javax.swing.GroupLayout(pnlSave1);
        pnlSave1.setLayout(pnlSave1Layout);
        pnlSave1Layout.setHorizontalGroup(
            pnlSave1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSave1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlSave1Layout.setVerticalGroup(
            pnlSave1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSave1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pnlEdit1.setBackground(new java.awt.Color(204, 204, 204));
        pnlEdit1.setPreferredSize(new java.awt.Dimension(90, 40));

        lblUpdate1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUpdate1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUpdate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/foodcitysystem/icon/note-interface-symbol.png"))); // NOI18N
        lblUpdate1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUpdate1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUpdate1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUpdate1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlEdit1Layout = new javax.swing.GroupLayout(pnlEdit1);
        pnlEdit1.setLayout(pnlEdit1Layout);
        pnlEdit1Layout.setHorizontalGroup(
            pnlEdit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUpdate1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );
        pnlEdit1Layout.setVerticalGroup(
            pnlEdit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUpdate1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        pnlRemove1.setBackground(new java.awt.Color(204, 204, 204));
        pnlRemove1.setPreferredSize(new java.awt.Dimension(90, 40));

        lblRemove1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRemove1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRemove1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/foodcitysystem/icon/recycle-bin.png"))); // NOI18N
        lblRemove1.setPreferredSize(new java.awt.Dimension(90, 40));
        lblRemove1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRemove1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRemove1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRemove1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlRemove1Layout = new javax.swing.GroupLayout(pnlRemove1);
        pnlRemove1.setLayout(pnlRemove1Layout);
        pnlRemove1Layout.setHorizontalGroup(
            pnlRemove1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRemove1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblRemove1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlRemove1Layout.setVerticalGroup(
            pnlRemove1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRemove1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pnlClear1.setBackground(new java.awt.Color(204, 204, 204));
        pnlClear1.setPreferredSize(new java.awt.Dimension(90, 40));

        lblClear1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblClear1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClear1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/foodcitysystem/icon/x-button.png"))); // NOI18N
        lblClear1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClear1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblClear1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblClear1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlClear1Layout = new javax.swing.GroupLayout(pnlClear1);
        pnlClear1.setLayout(pnlClear1Layout);
        pnlClear1Layout.setHorizontalGroup(
            pnlClear1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblClear1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );
        pnlClear1Layout.setVerticalGroup(
            pnlClear1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblClear1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlRemove1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlClear1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSave1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(pnlEdit1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(pnlRemove1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(pnlClear1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        pnlSave2.setBackground(new java.awt.Color(204, 204, 204));
        pnlSave2.setPreferredSize(new java.awt.Dimension(90, 40));

        lblSave2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSave2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSave2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/foodcitysystem/icon/save-icon-silhouette.png"))); // NOI18N
        lblSave2.setText(" ");
        lblSave2.setPreferredSize(new java.awt.Dimension(90, 40));
        lblSave2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSave2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSave2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSave2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlSave2Layout = new javax.swing.GroupLayout(pnlSave2);
        pnlSave2.setLayout(pnlSave2Layout);
        pnlSave2Layout.setHorizontalGroup(
            pnlSave2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSave2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblSave2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlSave2Layout.setVerticalGroup(
            pnlSave2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSave2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pnlEdit2.setBackground(new java.awt.Color(204, 204, 204));
        pnlEdit2.setPreferredSize(new java.awt.Dimension(90, 40));

        lblUpdate2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUpdate2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUpdate2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/foodcitysystem/icon/note-interface-symbol.png"))); // NOI18N
        lblUpdate2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUpdate2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUpdate2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUpdate2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlEdit2Layout = new javax.swing.GroupLayout(pnlEdit2);
        pnlEdit2.setLayout(pnlEdit2Layout);
        pnlEdit2Layout.setHorizontalGroup(
            pnlEdit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUpdate2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );
        pnlEdit2Layout.setVerticalGroup(
            pnlEdit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUpdate2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        pnlRemove2.setBackground(new java.awt.Color(204, 204, 204));
        pnlRemove2.setPreferredSize(new java.awt.Dimension(90, 40));

        lblRemove2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRemove2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRemove2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/foodcitysystem/icon/recycle-bin.png"))); // NOI18N
        lblRemove2.setPreferredSize(new java.awt.Dimension(90, 40));
        lblRemove2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRemove2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRemove2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRemove2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlRemove2Layout = new javax.swing.GroupLayout(pnlRemove2);
        pnlRemove2.setLayout(pnlRemove2Layout);
        pnlRemove2Layout.setHorizontalGroup(
            pnlRemove2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRemove2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblRemove2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlRemove2Layout.setVerticalGroup(
            pnlRemove2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRemove2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pnlClear2.setBackground(new java.awt.Color(204, 204, 204));
        pnlClear2.setPreferredSize(new java.awt.Dimension(90, 40));

        lblClear2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblClear2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClear2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/foodcitysystem/icon/x-button.png"))); // NOI18N
        lblClear2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClear2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblClear2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblClear2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlClear2Layout = new javax.swing.GroupLayout(pnlClear2);
        pnlClear2.setLayout(pnlClear2Layout);
        pnlClear2Layout.setHorizontalGroup(
            pnlClear2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblClear2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );
        pnlClear2Layout.setVerticalGroup(
            pnlClear2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblClear2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlSave2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlEdit2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlRemove2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlClear2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSave2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(pnlEdit2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(pnlRemove2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(pnlClear2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        lblNewCategory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNewCategory.setText("  ADD NEW");
        lblNewCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNewCategoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNewCategoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNewCategoryMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlNewCategoryLayout = new javax.swing.GroupLayout(pnlNewCategory);
        pnlNewCategory.setLayout(pnlNewCategoryLayout);
        pnlNewCategoryLayout.setHorizontalGroup(
            pnlNewCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNewCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
        );
        pnlNewCategoryLayout.setVerticalGroup(
            pnlNewCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNewCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        lblNewItem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNewItem.setText("  ADD NEW");
        lblNewItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNewItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNewItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNewItemMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlNewCategory2Layout = new javax.swing.GroupLayout(pnlNewCategory2);
        pnlNewCategory2.setLayout(pnlNewCategory2Layout);
        pnlNewCategory2Layout.setHorizontalGroup(
            pnlNewCategory2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNewItem, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
        );
        pnlNewCategory2Layout.setVerticalGroup(
            pnlNewCategory2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNewCategory2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblNewItem, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlNewCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCategoryCode, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(91, 91, 91)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCategoryName1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(jSeparator3))
                        .addGap(246, 246, 246))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(pnlNewCategory2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9)))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(113, 113, 113)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                                            .addComponent(jSeparator8)
                                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCategoryCode2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(txtCategoryName1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(pnlNewCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addGap(36, 36, 36)
                                            .addComponent(txtCategoryCode, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(50, 50, 50)))
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(pnlNewCategory2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtCategoryCode2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescriptionActionPerformed
       cmbCategoryName.requestFocus();
    }//GEN-LAST:event_txtDescriptionActionPerformed

    private void txtCategoryCode2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoryCode2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoryCode2ActionPerformed

    private void txtCategoryCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoryCodeActionPerformed
        txtCategoryName1.requestFocus();
    }//GEN-LAST:event_txtCategoryCodeActionPerformed

    private void txtCategoryName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoryName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoryName1ActionPerformed

    private void txtItemCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemCodeActionPerformed
        txtDescription.requestFocus();
        
    }//GEN-LAST:event_txtItemCodeActionPerformed

    private void lblSave1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSave1MouseClicked
         ItemDTO item=new ItemDTO(txtItemCode.getText(),
                    txtDescription.getText(),
                    (String)cmbCategoryName.getSelectedItem(),
                    txtCategoryCode2.getText()
            );
         DefaultTableModel dtm=(DefaultTableModel)tblItems.getModel();
         
         Object[] rowdata={
             item.getItemCode(),
             item.getDescription(),
             item.getCategoryName(),
             item.getCategoryCode()
             
         };
            
        try{    
            boolean result=ItemController.addItem(item);
            if(result){
                dtm.addRow(rowdata);
                
                JOptionPane.showMessageDialog(this, "Category has been successfully added.");
            }else{
                JOptionPane.showMessageDialog(this, "Category hasn't been added due to some error");
            }
        } catch (Exception ex) {
            Logger.getLogger(Item.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         
       
                                       

   
    }//GEN-LAST:event_lblSave1MouseClicked

    private void lblSave1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSave1MouseEntered
       pnlSave1.setBackground(new Color(36,113,163));
    }//GEN-LAST:event_lblSave1MouseEntered

    private void lblSave1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSave1MouseExited
        pnlSave1.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_lblSave1MouseExited

    private void lblUpdate1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdate1MouseClicked
         ItemDTO item=new ItemDTO(txtItemCode.getText(),
                    txtDescription.getText(),
                    (String)cmbCategoryName.getSelectedItem(),
                    txtCategoryCode2.getText()
            );
            
        try{    
            boolean result=ItemController.updateItem(item);
            if(result){
                
                
                JOptionPane.showMessageDialog(this, "Item has been successfully updated.");
            }else{
                JOptionPane.showMessageDialog(this, "Item hasn't been updated due to some error");
            }
        } catch (Exception ex) {
            Logger.getLogger(Item.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblUpdate1MouseClicked

    private void lblUpdate1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdate1MouseEntered
        pnlEdit1.setBackground(new Color(36,113,163));
    }//GEN-LAST:event_lblUpdate1MouseEntered

    private void lblUpdate1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdate1MouseExited
        pnlEdit1.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_lblUpdate1MouseExited

    private void lblRemove1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemove1MouseClicked
         ItemDTO item=new ItemDTO(txtItemCode.getText(),
                    txtDescription.getText(),
                    (String)cmbCategoryName.getSelectedItem(),
                    txtCategoryCode2.getText()
            );
            
        try{    
            boolean result=ItemController.deleteItem(item);
            if(result){
                
                
                JOptionPane.showMessageDialog(this, "Category has been successfully deleted.");
            }else{
                JOptionPane.showMessageDialog(this, "Category hasn't been deleted due to some error");
            }
        } catch (Exception ex) {
            Logger.getLogger(Item.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblRemove1MouseClicked

    private void lblRemove1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemove1MouseEntered
        
        pnlRemove1.setBackground(new Color(36,113,163));
    }//GEN-LAST:event_lblRemove1MouseEntered

    private void lblRemove1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemove1MouseExited
         pnlRemove1.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_lblRemove1MouseExited

    private void lblClear1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClear1MouseClicked
       txtItemCode.setText("");
       txtDescription.setText("");
    }//GEN-LAST:event_lblClear1MouseClicked

    private void lblClear1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClear1MouseEntered
       pnlClear1.setBackground(new Color(36,113,163));
    }//GEN-LAST:event_lblClear1MouseEntered

    private void lblClear1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClear1MouseExited
        pnlClear1.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_lblClear1MouseExited

    private void lblSave2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSave2MouseClicked
           ItemCategoryDTO itemCategory=new ItemCategoryDTO(txtCategoryCode.getText(),
                    txtCategoryName1.getText()
            );
            
        try{    
            boolean result=ItemCategoryController.addCategory(itemCategory);
            if(result){
                cmbCategoryName.addItem(txtCategoryName1.getText());
                
                JOptionPane.showMessageDialog(this, "Category has been successfully added.");
            }else{
                JOptionPane.showMessageDialog(this, "Category hasn't been added due to some error");
            }
        } catch (Exception ex) {
            Logger.getLogger(Item.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_lblSave2MouseClicked

    private void lblSave2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSave2MouseEntered
        pnlSave2.setBackground(new Color(36,113,163));
    }//GEN-LAST:event_lblSave2MouseEntered

    private void lblSave2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSave2MouseExited
         pnlSave2.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_lblSave2MouseExited

    private void lblUpdate2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdate2MouseClicked
         ItemCategoryDTO itemCategory=new ItemCategoryDTO(txtCategoryCode.getText(),
                    txtCategoryName1.getText()
            );
            
        try{    
            boolean result=ItemCategoryController.updateCategory(itemCategory);
            if(result){
               
                
                JOptionPane.showMessageDialog(this, "Category has been successfully updated.");
            }else{
                JOptionPane.showMessageDialog(this, "Category hasn't been updated due to some error");
            }
        } catch (Exception ex) {
            Logger.getLogger(Item.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblUpdate2MouseClicked

    private void lblUpdate2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdate2MouseEntered
       pnlEdit2.setBackground(new Color(36,113,163));
    }//GEN-LAST:event_lblUpdate2MouseEntered

    private void lblUpdate2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdate2MouseExited
       
        pnlEdit2.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_lblUpdate2MouseExited

    private void lblRemove2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemove2MouseClicked
        ItemCategoryDTO itemCategory=new ItemCategoryDTO(txtCategoryCode.getText(),
                    txtCategoryName1.getText()
            );
            
        try{    
            boolean result=ItemCategoryController.deleteCategory(itemCategory);
            if(result){
                
                
                JOptionPane.showMessageDialog(this, "Category has been successfully deleted.");
            }else{
                JOptionPane.showMessageDialog(this, "Category hasn't been deleted due to some error");
            }
        } catch (Exception ex) {
            Logger.getLogger(Item.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblRemove2MouseClicked

    private void lblRemove2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemove2MouseEntered
        pnlRemove2.setBackground(new Color(36,113,163));
    }//GEN-LAST:event_lblRemove2MouseEntered

    private void lblRemove2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemove2MouseExited
        pnlRemove2.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_lblRemove2MouseExited

    private void lblClear2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClear2MouseClicked
       txtCategoryCode.setText("");
       txtCategoryName1.setText("");
    }//GEN-LAST:event_lblClear2MouseClicked

    private void lblClear2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClear2MouseEntered
       pnlClear2.setBackground(new Color(36,113,163));
    }//GEN-LAST:event_lblClear2MouseEntered

    private void lblClear2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClear2MouseExited
        pnlClear2.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_lblClear2MouseExited

    private void lblNewCategoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewCategoryMouseEntered
       pnlNewCategory.setBackground(new Color(36,113,163));
       lblNewCategory.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lblNewCategoryMouseEntered

    private void lblNewItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewItemMouseEntered
       pnlNewCategory2.setBackground(new Color(36,113,163));
       lblNewItem.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lblNewItemMouseEntered

    private void lblNewCategoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewCategoryMouseExited
         pnlNewCategory.setBackground(new Color(204,204,204));
         lblNewCategory.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lblNewCategoryMouseExited

    private void lblNewItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewItemMouseExited
         pnlNewCategory2.setBackground(new Color(204,204,204));
         lblNewItem.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lblNewItemMouseExited

    private void lblNewCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewCategoryMouseClicked
       txtCategoryCode.requestFocusInWindow();
    }//GEN-LAST:event_lblNewCategoryMouseClicked

    private void lblNewItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewItemMouseClicked
        txtItemCode.requestFocusInWindow();
    }//GEN-LAST:event_lblNewItemMouseClicked

    private void cmbCategoryNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCategoryNameItemStateChanged
        try {
            ItemCategoryDTO itemCategory=new ItemCategoryDTO((String)cmbCategoryName.getSelectedItem());
            
            ItemCategoryDTO searchedCategory=ItemCategoryController.searchCategory(itemCategory);
            txtCategoryCode2.setText(searchedCategory.getCategoryCode());
            txtCategoryCode.setText(searchedCategory.getCategoryCode());
            txtCategoryName1.setText(searchedCategory.getCategoryName());
        } catch (Exception ex) {
            Logger.getLogger(Item.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_cmbCategoryNameItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCategoryName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblClear1;
    private javax.swing.JLabel lblClear2;
    private javax.swing.JLabel lblNewCategory;
    private javax.swing.JLabel lblNewItem;
    private javax.swing.JLabel lblRemove1;
    private javax.swing.JLabel lblRemove2;
    private javax.swing.JLabel lblSave1;
    private javax.swing.JLabel lblSave2;
    private javax.swing.JLabel lblUpdate1;
    private javax.swing.JLabel lblUpdate2;
    private javax.swing.JPanel pnlClear1;
    private javax.swing.JPanel pnlClear2;
    private javax.swing.JPanel pnlEdit1;
    private javax.swing.JPanel pnlEdit2;
    private javax.swing.JPanel pnlNewCategory;
    private javax.swing.JPanel pnlNewCategory2;
    private javax.swing.JPanel pnlRemove1;
    private javax.swing.JPanel pnlRemove2;
    private javax.swing.JPanel pnlSave1;
    private javax.swing.JPanel pnlSave2;
    private javax.swing.JTable tblItems;
    private javax.swing.JTextField txtCategoryCode;
    private javax.swing.JTextField txtCategoryCode2;
    private javax.swing.JTextField txtCategoryName1;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtItemCode;
    // End of variables declaration//GEN-END:variables

    private void loadAllCategoryNames() {
        try {
            ArrayList<ItemCategoryDTO>categoryNamesList=ItemCategoryController.getAllCategories();
            for(ItemCategoryDTO category:categoryNamesList){
                cmbCategoryName.addItem(category.getCategoryName());
            }
        } catch (Exception ex) {
            Logger.getLogger(Item.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadAllItems() {
        try {
            ArrayList<ItemDTO>allItems=ItemController.getAllItems();
            DefaultTableModel dtm=(DefaultTableModel)tblItems.getModel();
            dtm.setRowCount(0);
            
            if(allItems!=null){
                for(ItemDTO item:allItems){
                    
                    Object[] rowData={
                        item.getItemCode(),
                        item.getDescription(),
                        item.getCategoryName(),
                        item.getCategoryCode()
                        
                    };
                    dtm.addRow(rowData);
                    
                }
            }   } catch (Exception ex) {
            Logger.getLogger(Item.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
